services:
  postgresql:
    image: postgres:17
    container_name: payment-gateway-postgresql
    restart: unless-stopped
    env_file:
      - .env.docker.postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_user -d payment_gateway"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data:
    driver: local
